site_name: Relatório Técnico Docker
theme:
  name: material
nav:
  - Home: index.md
  - Docker Introdução: docker-introducao.md
  - Docker Instalação: docker-instalacao.md
  - Docker Imagens: docker-imagens.md
  - Docker Containers: docker-containers.md
  - Conclusão: conclusao.md
