site_name: Relatório Técnico Docker
theme:
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.sections
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.top
    - content.code.copy
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
nav:
  - Home: index.md
  - Introdução: docker-introducao.md
  - Instalação: docker-instalacao.md
  - Imagens: docker-imagens.md
  - Containers: docker-containers.md
  - Docker Compose: docker-compose.md
  - Conclusão: conclusao.md
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
